<h2>HOW TO SEARCH ARCHIVES</h2>
<h3>FIND BY KEYWORDS</h3>
<h4>How to Search</h4>
<p>Choose the field to search from the list of the search field form and enter the keyword in the keyword field and then hit the "RETURN" key. Hit key will be highlighten.(case sensitive)</p>
<h4>Search By Multiple Keywords</h4>
<ul>
<li>Separated by space : <span class="b"><strong>AND</strong></span> search</li>
<li>Separated by comma : <span class="b"><strong>OR</strong></span> search</li>
</ul>
<h2>Advances Search</h2>
<h3>Q: How can I search with other options？</h3>
<h4>A: You can use &quot;Advanced search&quot;.</h4>
<p>Here's how.</p>
<ol>
<li>Select the search target.</li>
<li>Enter the keywords. (separate with spaces)</li>
<li>Choose AND or OR.</li>
<li>Set date to search.(optional)</li>
<li>Select category (optional)</li>
<li>and... GO!</li>
</ol>
<p>Go to : <a href="../../search_plus.php" class="go"> SEARCH PLUS+</a></p>